- hosts: all
  become: yes
  become_user: root
  gather_facts: True


  tasks:
    - name: Add to hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
              - '{{ node1_private_ip }} {{ node1_name }}'
              - '{{ node2_private_ip }} {{ node2_name }}'
              - '{{ node3_private_ip }} {{ node3_name }}'
