- hosts: all
  become: true
  become_user: root
  gather_facts: True

  tasks:
    - name: Add apt-key
      command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

    - name: Import repo
      copy:
        dest: /etc/apt/sources.list.d/mongodb-org-4.0.list
        content: |
          deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse

    - name: Update
      command: apt update

    - name: Install
      command: apt-get install -y mongodb-org
