- hosts: node2
  become: true
  become_user: root
  gather_facts: True

  tasks:

    - name: Copiar el archivo de configuración Core-Site.XML
      ansible.builtin.template:
        src: node2.j2
        dest: /etc/mongod.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Restart mongo
      command: sudo systemctl restart mongod
